### ISSUE TITLE
Error during statup of Quarkus 3.0.0.Alpha6

### ISSUE THREAD

**Issue by nyko29** [quarkiverse/quarkus-jberet#195]
I am using the version 2.0.0 of the extension. My project is using quarkus 3.0.0.Alpha6 and in dev mode I have the following error during the starting of Quarkus.

```
2023-03-17 17:44:30,421 ERROR [io.qua.dev.dep.DevUIProcessor] (build-2) Failed to process extension descriptor jar:file:///home/nyko/.m2/repo/io/quarkiverse/jberet/quarkus-jberet/2.0.0/quarkus-jberet-2.0.0.jar!/META-INF/quarkus-extension.yaml: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at io.quarkus.devui.deployment.DevUIProcessor.lambda$getAllExtensions$1(DevUIProcessor.java:397)
	at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeAsPath$0(ClassPathUtils.java:121)
	at io.quarkus.runtime.util.ClassPathUtils.processAsPath(ClassPathUtils.java:154)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsPath(ClassPathUtils.java:120)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:104)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
	at io.quarkus.devui.deployment.DevUIProcessor.getAllExtensions(DevUIProcessor.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

Any  idea for the reason of this errror ?

**Comment by radcortez** [comment]
Hum... the PR to update to Alpha6 passed all the tests:
https://github.com/quarkiverse/quarkus-jberet/pull/194

In theory, it should work :)

Can you provide me with a reproducer? Thanks!

**Comment by amoscatelli** [comment]
Just start a quarkus:dev @radcortez
