### ISSUE TITLE
Quarkus jberet with Hibernate ORM fails to load `TenantResolver` in some cases

### ISSUE THREAD

**Issue by Malandril** [quarkiverse/quarkus-jberet#343]
# Bug
With quarkus jberet `2.4.0` and quarkus `3.14.2`
When using a custom `TenantResolver`with the disciriminator approach the Jberet job cannot seem to load the `TenantResolver` and throws 
```java
2024-09-05 19:30:24,728 WARN  [org.jberet] (executor-thread-2) JBERET000001: Failed to run batchlet org.jberet.job.model.RefArtifact@6a25ad02: org.hibernate.HibernateException: SessionFactory configured for multi-tenancy, but no tenant identifier specified
        at org.hibernate.internal.AbstractSharedSessionContract.setUpMultitenancy(AbstractSharedSessionContract.java:240)
        at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:273)
        at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1381)
        at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1247)
        at io.quarkus.hibernate.orm.runtime.session.JTASessionOpener.openSession(JTASessionOpener.java:46)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.acquireSession(TransactionScopedSession.java:92)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createSelectionQuery(TransactionScopedSession.java:1276)
        at org.hibernate.engine.spi.SessionLazyDelegator.createSelectionQuery(SessionLazyDelegator.java:749)
        at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.createSelectionQuery(Unknown Source)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:387)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:348)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:301)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:150)
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:24)
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:10)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.listAll(AbstractJpaOperations.java:309)
        at org.acme.MyEntity.listAll(MyEntity.java)
        at org.acme.JobFactory$Batchy.process(JobFactory.java:33)
        at org.acme.JobFactory_Batchy_Subclass.process$$superforward(Unknown Source)
        at org.acme.JobFactory_Batchy_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at org.acme.JobFactory_Batchy_Subclass.process(Unknown Source)
        at org.acme.JobFactory_Batchy_ClientProxy.process(Unknown Source)
        at org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:74)
        at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:226)
        at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:142)
        at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:170)
        at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:94)
        at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:58)
        at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:100)
        at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

Also something strange happens, if you wait the job with `awaitUntil` the tenant identifier will work correctly

# How to reproduce
I created a sample app using
`quarkus create app quarkus-jberet-session-bug  --gradle-kotlin-dsl --extension='rest-jackson,jberet,hibernate-orm-panache'`

You can clone the sample [https://github.com/Malandril/quarkus-jberet-session-bug](https://github.com/Malandril/quarkus-jberet-session-bug)

Then run a `quarkus dev`
After the applicaiton started, run  `curl localhost:8080/hello` the job will fail with `org.hibernate.HibernateException: SessionFactory configured for multi-tenancy, but no tenant identifier specified`

If you run `curl localhost:8080/hello/wait` the job won't fail

**Comment by radcortez** [comment]
This is because https://github.com/quarkusio/quarkus/blob/e5f2eaebaa364fe22532153fe46809ae965cf343/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/tenant/HibernateCurrentTenantIdentifierResolver.java#L33-L35.

Not sure why it checks for request scope to be active. In a Batch execution there is no request scope. It sometimes worked because the batch was executed before the request scope was removed.

One way to make it work is to annotate the batch component with `@ActivateRequestContext`. I do advise opening an issue in the Quarkus repo and discussing why that piece of code is there.
